'use client';
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { ACTIVITIES, CHAPTERS, ENDINGS, NPCS, STAT_LABELS } from '../data/game';
import { EVENTS, LAST_TURN, YOUTH_TURNS, average, beginMonth, careerScore, chapterOf, chooseEvent, dateLabel, effectsText, newGame, nextMonth, planActivity, playMatch, previewPlan, removeActivity, skipMatch, periodOf, stepLabel, isPro, clubLabel, recommendedPlan, reusePlan, seasonGoal, canContinueCareer, continueCareer } from '../engine/game';
import { mergeCollection, parseSave, readCollection, readSave, serializeSave, writeSave, type Collection } from '../engine/save';
import { statKeys, type GameState } from '../engine/types';
import { AppTools } from './pwa';

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return ()=>ref.current?.close();},[]);return <dialog ref={ref} onCancel={onClose} aria-label={title}><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="닫기">×</button></div>{children}</dialog>;}
function Meter({label,value,tone='lime'}:{label:string;value:number;tone?:string}){return <div className="meter"><div><span>{label}</span><strong>{Math.round(value)}<small>/100</small></strong></div><div className="bar"><i className={tone} style={{width:`${value}%`}}/></div></div>;}
const matchNames=['왼발로 직접 슛','동료에게 패스','드리블로 돌파','안전하게 볼 지키기'];
const matchDescriptions=['득점에 도전한다. 슈팅 · 멘탈','동료의 골을 돕는다. 패스 · 시야 · 팀워크','공간을 직접 만든다. 드리블 · 스피드','현재 스코어를 지킨다. 멘탈 · 볼 컨트롤'];
export default function Home(){
 const [game,setGame]=useState<GameState>(()=>newGame(200701));const [collection,setCollection]=useState<Collection>({events:[],endings:[]});const [ready,setReady]=useState(false);const [view,setView]=useState('play');const [modal,setModal]=useState<string|null>(null);const [notice,setNotice]=useState('');const [storageError,setStorageError]=useState(false);const [autosaveBlocked,setAutosaveBlocked]=useState(false);const fileRef=useRef<HTMLInputElement>(null);const turnHeading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{let found:Collection={events:[],endings:[]};try{found=readCollection();}catch{}setCollection(found);try{const loaded=readSave();setGame(loaded?.state||newGame());setCollection(mergeCollection(found,loaded?.collection||{events:[],endings:[]}));}catch{setGame(newGame());setAutosaveBlocked(true);setNotice('자동 저장을 읽지 못해 원본을 보존했습니다. 저장 관리에서 수동 저장을 불러오거나 새 게임을 시작해 주세요.');}setReady(true);},[]);
 useEffect(()=>{if(!ready||autosaveBlocked)return;const merged=mergeCollection(collection,{events:game.seenEvents,endings:game.endingId?[game.endingId]:[]});if(JSON.stringify(merged)!==JSON.stringify(collection))setCollection(merged);try{writeSave(game,merged);setStorageError(false);}catch{setStorageError(true);}},[game,ready,collection,autosaveBlocked]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),7000);return()=>clearTimeout(timer);},[notice]);
 const chapter=chapterOf(game),c=CHAPTERS[chapter],period=periodOf(game.turn),pro=isPro(game),goal=seasonGoal(game),preview=previewPlan(game),event=EVENTS.find(e=>e.id===game.eventId),ending=ENDINGS.find(e=>e.id===game.endingId);
 const endingTitle=pro?({europe:'유럽에서 다음 계약으로',domestic:'우리 리그의 주전으로',academy:'한 시즌 더, 끝나지 않은 도전'} as Record<string,string>)[game.endingId||'']:ending?.title;
 const endingBody=pro?`${period.age}세, 세 시즌의 기록을 남겼다. ${game.seasons.filter(s=>s.goalMet).length}개의 시즌 목표를 달성했고, 다음 계약을 향한 평가가 나왔다. 이 인생은 여기서 잠시 저장된다. 은퇴까지의 긴 커리어는 다음 확장에서 이어진다.`:ending?.body;
 const commit=(s:GameState)=>{setGame(s);setView('play');setTimeout(()=>turnHeading.current?.focus(),0);};
 const save=()=>{try{writeSave(game,collection,true);setNotice('현재 인생을 수동 저장했습니다.');}catch{setNotice('저장 공간을 사용할 수 없습니다. 파일로 내보내 주세요.');}};
 const load=()=>{try{const data=readSave(true);if(!data){setNotice('수동 저장이 없습니다. 먼저 저장해 주세요.');return;}setGame(data.state);setAutosaveBlocked(false);setCollection(mergeCollection(collection,data.collection));setModal(null);setView('play');setNotice('수동 저장을 불러왔습니다.');}catch{setNotice('수동 저장이 올바르지 않습니다. 현재 게임은 유지했습니다.');}};
 const exportSave=()=>{const blob=new Blob([serializeSave(game,collection)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`kang-in-${dateLabel(game.turn)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('저장 파일을 내보냈습니다.');};
 const importSave=async(file?:File)=>{if(!file)return;try{if(file.size>2_000_000)throw new Error('too large');const data=parseSave(await file.text());setGame(data.state);setAutosaveBlocked(false);setCollection(mergeCollection(collection,data.collection));setModal(null);setView('play');setNotice('저장 파일을 가져왔습니다.');}catch{setNotice('이 게임의 정상 저장 파일인지 확인해 주세요. 현재 기록은 유지했습니다.');}if(fileRef.current)fileRef.current.value='';};
 const recent=game.logs.filter(l=>l.kind!=='training').slice(0,3);
 return <div className={`game-shell ${game.phase==='planning'&&view==='play'?'is-planning':''}`} data-app-id="kang-in">
  <header className="topbar"><a className="brand" href="#game" aria-label="이강인 키우기"><span className="brand-mark">K</span><span>이강인 키우기<small>육성 게임 / 저장 슬롯 01</small></span></a><span className="edition">KANG-IN.EXE</span><div className="header-actions"><button onClick={()=>setModal('help')} className="quiet">도움말</button><button onClick={()=>setModal('save')} className="outline">저장</button></div></header>
  <AppTools onGuide={()=>setModal('install')}/>
  <main id="game"><div className="chapter-track" aria-label="성장 단계">{CHAPTERS.map((ch,i)=><div key={ch.year} className={`chapter-step ${i===chapter?'active':''} ${i<chapter?'past':''}`}><span className="chapter-number">0{i+1}</span><div><small>{ch.age}세 · {ch.year}</small><strong><span className="chapter-name">{ch.name}</span><span className="chapter-age">{ch.age}세</span></strong></div>{i===chapter&&<span className="chapter-status">진행 중</span>}</div>)}</div>
   <div className="workspace">
    <aside className="player-panel"><div className="player-art"><img src="./retro-kid.png" alt="빨간 유니폼과 축구공을 가진 장난꾸러기 소년 도트 캐릭터"/><div className="card-top"><span>PLAYER 1</span><span className="card-number">{period.age}세</span></div><div className="player-caption"><span className="position-badge">{game.position} · 왼발</span><h1>이강인</h1><div><span>종합 <b>{Math.round(average(game))}</b></span><span>{clubLabel(game)}</span></div></div><small className="art-credit">{pro?'왼발 하나로 다음 무대!':'공 하나면 하루 종일!'}</small></div>
     <details className="player-stats"><summary>능력치 보기 <b>{Math.round(average(game))}</b></summary><div className="stats-grid">{statKeys.map(k=><div className="stat-row" key={k}><span>{STAT_LABELS[k]}</span><div className="mini-bar"><i style={{width:`${game.stats[k]}%`}}/></div><b>{Math.round(game.stats[k])}</b></div>)}</div><div className="player-traits"><span>왼발의 재능</span><span>{game.position==='CAM'?'창의적인 플레이메이커':game.position==='RW'?'과감한 윙어':'꾸준한 중원 엔진'}</span></div></details>
    </aside>
    <section className="main-panel">
     <div className="month-header"><div><p className="eyebrow">CHAPTER 0{chapter+1} / {c.name}</p><h2 ref={turnHeading} tabIndex={-1}>{period.year}<span>년</span> {period.month}<span>월</span></h2><p>{c.description}</p><span className="pace-label">{period.age}세 · {stepLabel(game.turn)}씩 진행</span></div><div className="turn-count"><strong>{pro?game.turn-YOUTH_TURNS+1:game.turn+1}<span>/{pro?36:16}</span></strong><small>{pro?'프로 시즌':'빠른 성장'}</small></div></div>
     <div className="vitals"><Meter label="컨디션" value={game.condition}/><Meter label="피로" value={game.fatigue} tone={game.fatigue>70?'red':'blue'}/><Meter label="행복" value={game.happiness} tone="pink"/><Meter label="신뢰" value={game.trust} tone="gold"/></div>
     <nav className="tabs" aria-label="게임 화면">{[['play','육성'],['career','선수'],['journal','기록'],['collection','도감']].map(([id,label],i)=><button key={id} aria-current={view===id?'page':undefined} className={view===id?'selected':''} onClick={()=>{setView(id);window.scrollTo({top:0,behavior:'instant'});}}><span aria-hidden="true">0{i+1}</span>{label}</button>)}</nav>
     <div className="play-surface">
     {!ready?<p className="loading">성장 기록을 불러오는 중…</p>:view==='play'?<>
      {game.phase==='planning'&&<><div className="section-line"><div><p className="eyebrow">GROWTH PLAN</p><h3>{stepLabel(game.turn)} 동안의 활동</h3></div><span className="slot-count">{game.plan.length} / 3 선택</span></div><p className="muted">활동 세 가지를 고르세요. 같은 활동은 최대 두 번.</p><div className="quick-plans"><button className="outline" onClick={()=>setGame(recommendedPlan(game))}>추천 계획 채우기</button><button className="outline" disabled={game.previousPlan.length!==3} onClick={()=>setGame(reusePlan(game))}>이전 계획 다시</button></div>{goal&&game.season&&<div className="season-goal"><div><small>{game.season.year} 시즌 목표</small><strong>{goal.label}</strong><span>{goal.achieved?'달성!':`${goal.progress} / ${goal.target}`}</span></div><p>{goal.detail}</p><small>현재 {game.season.appearances}회 출전 · {game.season.goals}골 {game.season.assists}도움 · 신뢰 {Math.round(game.trust)} · 팀워크 {Math.round(game.teamwork)} · 평균 평점 {game.season.appearances?(game.season.ratingTotal/game.season.appearances).toFixed(1):'—'}</small></div>}
       <div className="plan-slots">{[0,1,2].map(i=><button key={i} className={game.plan[i]?'filled':''} onClick={()=>setGame(removeActivity(game,i))} disabled={!game.plan[i]} aria-label={game.plan[i]?`${i+1}번 ${ACTIVITIES.find(a=>a.id===game.plan[i])?.name} 제거`:`${i+1}번 빈 활동 슬롯`}><span className="slot-index">0{i+1}</span>{game.plan[i]?<><b>{ACTIVITIES.find(a=>a.id===game.plan[i])?.name}</b><span aria-hidden="true">×</span></>:<span>선택 대기</span>}</button>)}</div>
       {game.injuryMonths>0&&<p className="alert">회복이 필요해요. 휴식 · 가족을 선택하면 경기 복귀를 준비할 수 있어요.</p>}
       <div className="activity-grid">{ACTIVITIES.map(a=>{const count=game.plan.filter(x=>x===a.id).length;return <button key={a.id} className={`activity ${count?'picked':''}`} disabled={game.plan.length>=3||count>=2} onClick={()=>setGame(planActivity(game,a.id))} aria-label={`${a.name} 선택. ${effectsText(a.effects)}`}><div className="activity-top"><span className="activity-icon">{a.icon}</span><span className="activity-type">{count?`${count}회 선택`:a.group}</span></div><h4>{a.name}</h4><p>{a.subtitle}</p><small>{effectsText(a.effects)}</small></button>;})}</div>
       <div className="plan-footer"><div><span className="muted">활동 후 예상</span><p>컨디션 <b>{Math.round(preview.condition)}</b> · 피로 <b className={preview.fatigue>70?'danger':''}>{Math.round(preview.fatigue)}</b>{preview.fatigue>70&&<span className="danger"> · 부상 위험 증가</span>}</p></div><button className="primary" disabled={game.plan.length!==3} onClick={()=>commit(beginMonth(game))}>{stepLabel(game.turn)} 진행 <span>{game.plan.length}/3</span></button></div>
       <div className="coach-tip"><span>COACH NOTE</span><p>{game.fatigue>60?'지금은 회복도 훈련만큼 중요해. 잠깐 쉬어도 재능은 사라지지 않아.':chapter===0?'잘하는 것 하나, 배우고 싶은 것 하나, 그리고 쉴 시간. 좋은 성장 계획은 균형에서 시작해.':game.route==='spain'&&game.language<30?'좋은 패스는 말에서도 시작해. 스페인어를 배우면 다음 무대에 적응하기 쉬워질 거야.':'큰 팀의 이름보다 내가 뛸 수 있는 자리가 중요해. 실력과 감독의 믿음을 함께 쌓아보자.'}</p></div></>}
      {game.phase==='event'&&event&&<div className="event-scene"><p className="eyebrow">LIFE EVENT · {event.category}</p><div className="event-symbol">✦</div><h3>{event.title}</h3><p className="event-body">{event.body}</p>{event.condition?.flag&&<p className="butterfly-note">이전에 남긴 선택이 새로운 사건으로 이어졌어요.</p>}<div className="choices">{event.choices.map((choice,i)=><button key={i} onClick={()=>commit(chooseEvent(game,i))}><span className="choice-number">0{i+1}</span><div><strong>{choice.label}</strong><p>{choice.description}</p><small>{effectsText(choice.effects)}{choice.route&&` · ${choice.route==='spain'?'스페인':'국내'} 경로`}{choice.position&&` · ${choice.position}`}</small></div></button>)}</div></div>}
      {game.phase==='match'&&game.match&&<div className="match-scene"><p className="eyebrow">MATCH DAY · {game.match.context||'대표 경기'}</p><div className="scoreboard"><span>우리 팀</span><strong>{game.match.home} <em>:</em> {game.match.away}</strong><span>{game.match.opponent}</span></div><div className="pitch-diagram" aria-hidden="true"><div className="center-circle"/><span className="ball-marker">87′</span><span className="pitch-position">오른쪽 페널티박스 앞</span></div><h3>{game.injuryMonths?'이번 경기는 회복에 집중하자':'공이 왼발 앞에 놓였다.'}</h3><p className="muted">{game.injuryMonths?'벤치에서도 함께 뛰는 마음은 같아. 다음 활동엔 휴식을 계획해요.':'후반 87분. 한 번의 판단으로 경기를 바꿀 수 있다.'}</p><div className="choices match-choices">{game.injuryMonths?<button className="primary" onClick={()=>commit(playMatch(game,3))}>팀을 응원하며 회복하기</button>:matchNames.map((name,i)=><button key={name} onClick={()=>commit(playMatch(game,i))}><span className="choice-number">0{i+1}</span><div><strong>{name}</strong><p>{matchDescriptions[i]}</p></div><span className="probability">{game.match!.probabilities[i]}%<small>성공 확률</small></span></button>)}</div><button className="text-button recovery-button" onClick={()=>commit(skipMatch(game))}>이번 경기는 쉬고 회복하기 · 신뢰 -2</button><p className="fine-print">확률에는 능력, 상대 수준, 컨디션, 피로가 반영됩니다. 성공을 보장하지 않아요.</p></div>}
      {game.phase==='summary'&&game.match&&<div className="summary-scene"><p className="eyebrow">GROWTH IN REVIEW</p><h3>{stepLabel(game.turn)} 더, 성장했다.</h3><div className="result-score">{game.match.home}<span>:</span>{game.match.away}<small>{game.match.played?`경기 평점 ${game.match.rating}`:'경기 휴식'}</small></div><p className="event-body">{game.match.result}</p><div className="gain-list">{statKeys.filter(k=>(game.lastGains[k]||0)>0).map(k=><span key={k}>{STAT_LABELS[k]} <b>+{Math.round((game.lastGains[k]||0)*10)/10}</b></span>)}</div><div className="month-events">{game.logs.filter(l=>l.turn===game.turn&&!l.legacy&&l.kind==='butterfly').map((l,i)=><p key={i}>✦ {l.body}</p>)}</div>{game.turn<LAST_TURN&&<p className="chapter-notice">다음: {dateLabel(game.turn+1)} · {periodOf(game.turn+1).age}세. {game.turn===YOUTH_TURNS-1?'프로로 나아가면 이제 한 달씩 진행합니다.':'대표 경기만 기록에 더합니다.'}</p>}<button className="primary wide" onClick={()=>commit(nextMonth(game))}>{game.turn===LAST_TURN?'세 시즌의 결과 보기':game.turn===YOUTH_TURNS-1?'스무 살, 다음 무대로':`다음 ${stepLabel(game.turn+1)}으로`}</button></div>}
      {game.phase==='ended'&&ending&&<div className="ending-scene"><p className="eyebrow">{pro?'THREE SEASONS COMPLETE':'YOUR FIRST CHAPTER IS COMPLETE'}</p><div className="ending-emblem" style={{color:ending.color}}>✦</div><p className="ending-subtitle">{ending.subtitle}</p><h3>{endingTitle}</h3><p className="event-body">{endingBody}</p><div className="career-numbers"><div><strong>{careerScore(game)}</strong><span>커리어 점수 / 100</span></div><div><strong>{game.matches}</strong><span>경기</span></div><div><strong>{game.goals}</strong><span>골</span></div><div><strong>{game.assists}</strong><span>도움</span></div></div>{canContinueCareer(game)&&<><p className="chapter-notice">이전 버전에서 마친 인생입니다. 기록을 보존한 채 20세 프로 시즌으로 이어갈 수 있어요.</p><button className="primary wide" onClick={()=>commit(continueCareer(game))}>이 인생으로 프로 시즌 계속</button></>}<p className="muted">이번 선택의 기록은 도감에 남아요.</p><div className="ending-actions"><button className="primary" onClick={()=>setModal('new')}>새로운 인생 시작</button><button className="outline" onClick={exportSave}>이 인생 저장하기</button></div></div>}
     </>:view==='career'?<div className="career-view"><p className="eyebrow">CAREER PROFILE</p><h3>나를 만드는 사람들</h3><div className="career-numbers"><div><strong>{game.matches}</strong><span>경기</span></div><div><strong>{game.goals}</strong><span>골</span></div><div><strong>{game.assists}</strong><span>도움</span></div><div><strong>{game.wins}</strong><span>승리</span></div></div><div className="extra-metrics"><Meter label="스페인어" value={game.language} tone="blue"/><Meter label="팀워크" value={game.teamwork}/><Meter label="인지도" value={game.popularity} tone="pink"/></div><div className="relation-list">{NPCS.map((n,i)=><div className="relation" key={n.id}><span className="npc-avatar">{String(i+1).padStart(2,'0')}</span><div><strong>{n.name}</strong><small>{n.role}</small></div><span>{Math.round(game.relations[n.id])}<small>관계</small></span></div>)}</div><p className="fine-print">보조 인물은 모두 역할 기반 가상 인물입니다. 훈련과 사건 선택으로 관계가 변화합니다.</p>{game.seasons.length>0&&<div className="season-history">{game.seasons.map(s=><p key={s.year}><b>{s.year}</b> · {s.appearances}회 출전 · {s.goals}골 {s.assists}도움 · 목표 {s.goalMet?'달성':'미달'}</p>)}</div>}<details className="ending-guide"><summary>계약 평가의 조건 확인</summary><p>유럽 계약: 스페인 경로 · 종합 60 이상 · 신뢰 55 이상 · 스페인어 30 이상 · 부상 없음<br/>국내 프로 계약: 종합 48 이상 · 신뢰 45 이상 · 부상 없음<br/>방송·콘텐츠 또는 평범한 삶: 마지막 진로 선택을 우선 반영<br/>다른 경우: 프로 도전팀에서 한 시즌 더 도전</p></details></div>:view==='journal'?<div className="journal-view"><p className="eyebrow">THE BUTTERFLY EFFECT</p><h3>작은 선택이 만든 이야기</h3><div className="journal-list">{game.logs.map((l,i)=><article key={i} className={l.kind==='butterfly'?'butterfly-log':''}><span className="journal-date">{l.date||dateLabel(l.turn)}</span><div><span className="log-kind">{({training:'훈련',event:'사건',match:'경기',chapter:'새로운 장',butterfly:'나비효과'})[l.kind]}</span><h4>{l.title}</h4><p>{l.body}</p>{l.changes&&<small>{effectsText(l.changes)}</small>}</div></article>)}</div></div>:<div className="collection-view"><p className="eyebrow">YOUR COLLECTION</p><h3>다시 시작할 이유</h3><div className="collection-counts"><span>발견한 사건 <b>{collection.events.length}<small> / {EVENTS.length}</small></b></span><span>발견한 엔딩 <b>{collection.endings.length}<small> / 5</small></b></span></div><div className="ending-list">{ENDINGS.map(e=><article key={e.id} className={collection.endings.includes(e.id)?'unlocked':''}><span>✦</span><div><small>{collection.endings.includes(e.id)?e.subtitle:'UNDISCOVERED'}</small><h4>{collection.endings.includes(e.id)?e.title:'아직 펼치지 않은 이야기'}</h4></div></article>)}</div><div className="event-collection">{EVENTS.map(e=><div key={e.id} className={collection.events.includes(e.id)?'discovered':''}><small>{e.id.toUpperCase()}</small><span>{collection.events.includes(e.id)?e.title:'???'}</span></div>)}</div><p className="fine-print">발견한 사건과 엔딩은 새 게임을 시작해도 남습니다. 이 브라우저의 저장 공간을 사용합니다.</p></div>}
     </div>
    </section>
   </div>
   {view==='journal'&&<section className="news-feed"><div className="news-heading"><span className="eyebrow">TOUCHLINE NEWS</span><h2>운동장 밖의 이야기</h2><small>게임 속 가상 소식</small></div><div className="news-items">{recent.map((l,i)=><article key={i}><span>{l.date||dateLabel(l.turn)} · {l.kind==='match'?'MATCH REPORT':l.kind==='butterfly'?'BUTTERFLY EFFECT':'CAREER NEWS'}</span><h3>{l.title}</h3><p>{l.body}</p></article>)}</div></section>}
  </main><footer><span>PROJECT KANG-IN <b>v0.4</b></span><p>팬 창작 육성게임 · 선수·구단과 무관한 비공식 작품 · 사건·일정·계약은 허구</p><span>{autosaveBlocked?'자동 저장 복구 필요':storageError?'저장 불가 · 파일 내보내기 필요':ready?'기기 내 자동 저장':'불러오는 중'}</span></footer>
  {notice&&<div role="status" className="toast">{notice}<button onClick={()=>setNotice('')} aria-label="알림 닫기">×</button></div>}
  <input ref={fileRef} type="file" accept=".json,application/json" className="visually-hidden" aria-label="저장 파일 가져오기" onChange={e=>void importSave(e.target.files?.[0])}/>
  {modal==='save'&&<Modal title="나의 인생 저장" onClose={()=>setModal(null)}><p className="muted">선택할 때마다 이 브라우저에 자동 저장합니다. 앱 설치나 다른 주소·기기로 옮길 때는 파일을 내보내고 가져오세요.</p><div className="save-grid"><button className="outline" onClick={save}>수동 저장</button><button className="outline" onClick={load}>수동 저장 불러오기</button><button className="outline" onClick={exportSave}>파일로 내보내기</button><button className="outline" onClick={()=>fileRef.current?.click()}>파일 가져오기</button></div><button className="text-button" onClick={()=>setModal('new')}>새 게임 시작</button>{notice&&<p className="modal-status" role="status">{notice}</p>}</Modal>}
  {modal==='new'&&<Modal title="새로운 인생을 시작할까요?" onClose={()=>setModal(null)}><p className="muted">현재 자동 저장은 새 게임으로 바뀝니다. 발견한 도감은 남아요. 현재 인생을 보관하려면 먼저 파일로 내보내세요.</p><div className="modal-actions"><button className="outline" onClick={exportSave}>현재 인생 내보내기</button><button className="primary" onClick={()=>{setGame(newGame());setAutosaveBlocked(false);setView('play');setModal(null);setNotice('2007년, 새로운 가능성이 시작됩니다.');}}>새 인생 시작</button></div></Modal>}
  {modal==='install'&&<Modal title="홈 화면에 설치하기" onClose={()=>setModal(null)}><ol className="guide-list"><li><strong>안드로이드</strong><p>Chrome에서 게임 주소를 연 뒤 메뉴의 ‘앱 설치’ 또는 ‘홈 화면에 추가’를 선택하세요. 설치 버튼이 보이면 바로 사용할 수 있어요.</p></li><li><strong>아이폰 · 아이패드</strong><p>Safari에서 게임 주소를 열고 공유 버튼을 누른 뒤 ‘홈 화면에 추가’를 선택하세요.</p></li><li><strong>연결 없이도 한 번 더</strong><p>처음에는 인터넷에 연결해 게임을 열어 주세요. 오프라인 준비를 마치면 연결 없이도 플레이할 수 있습니다. 저장은 기기 안에 남아요.</p></li></ol><p className="fine-print">앱이나 주소가 바뀌기 전에는 저장 관리에서 파일을 내보내 두세요. 브라우저와 설치 앱의 저장 공간이 서로 다를 수 있습니다.</p><button className="primary wide" onClick={()=>setModal(null)}>확인</button></Modal>}
  {modal==='help'&&<Modal title="작은 왼발을 키우는 방법" onClose={()=>setModal(null)}><ol className="guide-list"><li><strong>한 기간에 세 가지 활동</strong><p>훈련으로 실력을, 팀 활동으로 신뢰를 쌓으세요. 카드에는 기본 효과가 표시되며 실제 성장은 연령·숙련도·포지션에 따라 달라집니다. 피로가 75를 넘으면 부상 위험이 생깁니다.</p></li><li><strong>사건과 경기에서 선택</strong><p>선택의 효과와 경기 확률을 확인하세요. 확률은 상대와 컨디션에 따라 달라집니다.</p></li><li><strong>작은 선택을 오래 기억</strong><p>언어 공부와 가족 시간은 나중의 기회에 영향을 줍니다. 선택의 기록에서 원인을 확인하세요.</p></li><li><strong>스무 살까지 빠르게, 이후엔 한 달씩</strong><p>6~17세는 1년, 18~19세는 6개월씩 성장합니다. 20세부터는 36개월의 프로 시즌을 즐겨요. 추천·이전 계획 버튼으로 반복 선택을 줄일 수 있습니다. 축구 밖의 진로는 19세에서 마무리됩니다.</p></li></ol><p className="fine-print">각 기간에는 대표 경기 한 번을 진행하며 실제 경력의 재현이 아닌 가상 세계선입니다. 키보드 Tab과 Enter로도 모든 선택을 할 수 있습니다.</p><button className="primary wide" onClick={()=>setModal(null)}>내 인생으로 돌아가기</button></Modal>}
 </div>;
}





